server:
  port: 8083
  
spring:
 boot:
   admin:
     client:
       url: http://172.23.239.225:8000
cloud:
    config:
      uri:  http://172.23.239.225:8060   
application:
   name: calendar-service
   