

spring:
 boot:
   admin:
     client:
       url: http://172.23.239.225:8000
 cloud:
    config:
      uri:  http://172.23.239.225:8888   
 application:
   name: doctorAuth

info:
 app:
   description: Doctor service is up and has no problem
   name: Doctor-Auth
   version: 1.0.0

  
