
server:
  port: 8080
  
spring:
   data:
       mongodb:
           database: DoctorServiceDbMongo
           host: localhost
           password: root123
           port: 27017
           username: jason