
server:
  port: 8091
  
spring:
<<<<<<< HEAD
 boot:
   admin:
     client:
       url: http://172.23.239.225:8000
 cloud:
    config:
      uri:  http://172.23.239.225:8060   
 application:
   name: doctor-services
=======
   data:
       mongodb:
           database: DoctorServiceDbMongo
           host: localhost
           password: root123
           port: 27017
           username: json
>>>>>>> efad7ded8c32abff426a103cb43029dec8f350b9
