
server:
  port: 8081
  
spring:
   data:
       mongodb:
           database: DoctorServiceDbMongo
           host: localhost
           password: root1234
           port: 27017
           username: sanvi