server:
  port: 9002
spring:
  application:
    name: PatientAuth
  datasource:
    url: jdbc:mysql://172.23.239.158:3306/PatientAuthDBMySQL
    username: root
    password: root123
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  
  boot:
    admin:
      client:
        url:
        - http://localhost:9000
    
    
    
