spring:
  jpa:
    show-sql: true
    hibernate:
           ddl-auto: update
  boot:
    admin:
     client:
     url:
     - http://172.23.239.225:9000

  application:
    name: DoctorAuth


  datasource:
     url: jdbc:mysql://172.23.239.229:3306/doctorAuthenDb
     username: root
     password: root