spring:
  jpa:
    show-sql: true
    hibernate:
           ddl-auto: update
  boot:
    admin:
     client:
     url:
     - http://172.23.239.225:9000

  application:
    name: PatientAuth


  datasource:
     url: jdbc:mysql://172.23.239.158:3306/PatientAuthDBMySQL
     username: root
     password: root123