server:
  port: 8888
  
spring:
  application:
    name: ConfigService
  boot:
    admin:
      client:
        url:
        - http://172.23.239.225:8000
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sonu3706/spring-cloud-config-demo

      
      
   

   
   
   