server:
 port: 8085

spring:
<<<<<<< HEAD
   data:
       mongodb:
           database: BookingService
           host: localhost
           password: root123
           port: 27017
           username: root123
=======
  data:
      mongodb:
          database: BookingService
          host: localhost
          password: root
          port: 27017
          username: root1
>>>>>>> ecb94b942a725379021b234edae8e8c2ef4c6e63
