server:
  port: 8081
  
spring:
   data:
       mongodb:
           database: BookingService
           host: localhost
           password: root123
           port: 27017
           username: root123